config/routes.rb
Rails.application.routes.draw do
resources :taches, except: [:show]

  root to: "taches#index"

end

app/models/tache.rb
class Tache
  include Mongoid::Document
  field :nom, type: String
  field :societe, type: String
  field :montant, type: String
  field :date, type: String
  field :notes, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/taches_controller.rb
class TachesController < ApplicationController
 def index
    @tache = Tache.all
  end

  def new
    @tache = Tache.new
  end

  def create
    @tache = Tache.new(tache_params)

    if @tache.save
      redirect_to taches_path, notice: "Enregistré" and return
    end
    render 'new'
  end

  def edit
    @tache = Tache.find(params[:id])
  end

  def update
    @tache = Tache.find(params[:id])

    if @tache.update_attributes(tache_params)
      redirect_to taches_path, notice: "Frais mis à jour!" and return
    end

    render 'edit'
  end

  def destroy
    @tache = Tache.find(params[:id])
    @tache.destroy

    redirect_to taches_path, notice: "Frais supprimé!" and return
  end
private
  def tache_params
    params.require(:tache).permit(:nom, :societe, :montant, :date, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/taches_helper.rb
module TachesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/taches/_form.html.erb
<%= form_for @tache do |f| %>
  <div class="form-group">
    <%= f.label :nom %>
    <%= f.text_field :nom, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :societe %>
    <%= f.text_field :societe, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :montant %>
    <%= f.text_field :montant, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :date %>
    <%= f.text_field :date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: "form-control" %>
  </div>
  <%= f.submit "Enregistrer frais", class: "btn btn-primary" %>
<% end %>

app/views/taches/edit.html.erb
<h1>Nouveau paiement</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/taches/index.html.erb
<h1>Gestion de nos dépenses</h1>
<div class="well">
  <%= link_to "Nouveau frais", new_tach_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Intitulé</th>
      <th>Société</th>
      <th>Montant</th>
      <th>Date</th>
      <th>Notes</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @tache.size == 0 %>
      <tr>
        <td colspan="7">Pas de frais</td>
      </tr>
    <% else %>
      <% @tache.each do |tache| %>
        <tr>
          <td><%= tache.nom %></td>
          <td><%= tache.societe %></td>
          <td><%= tache.montant %></td>
          <td><%= tache.date %></td>
          <td><%= tache.notes %></td>
          <td>
            <%= link_to "Editer", edit_tach_path(tache), class: "btn btn-default" %>
          </td>
          <td>
            <%= button_to "Supprimer", tache, method: :delete, data: { confirm: "Confirmes-tu la suppression ?" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/taches/new.html.erb
<h1>Nouveau paiement</h1>
<div class="well">
  <%= render "form" %>
</div>